name: Maven CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Garantir permissao do Maven Wrapper
        run: chmod +x mvnw

      - name: Build com Maven
        run: ./mvnw -B clean package -DskipTests
